notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: bionic
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
addons:
  apt:
    packages:
      - apt-transport-https
      - gnupg
      - lsb-release
      - wget
before_install:
  - sudo wget -O /usr/share/keyrings/apache-arrow-keyring.gpg
      https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-keyring.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/apache-arrow-keyring.gpg] https://dl.bintray.com/apache/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/ $(lsb_release --codename --short) main" |
      sudo tee /etc/apt/sources.list.d/apache-arrow.list
  - sudo apt update -qq
  - gem update bundler
